name             'dotfiles'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dotfiles'
long_description 'Installs/Configures dotfiles'
version          '0.1.0'
depends          'vim'
